services:
  - type: web
    name: botvalle
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: free
    autoDeploy: true
    runtime: python
    region: oregon
